---

- name: Fail if required authentik settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - authentik_hostname
    - authentik_database_hostname
    - authentik_database_username
    - authentik_database_password
    - authentik_secret_key
    - authentik_config_redis_hostname
